package:
  name: snpahoy
  version: '0.5'

source:
  git_rev: v0.5
  git_url: git@github.com:micknudsen/snpahoy.git

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - pysam >=0.15
    - python >=3.6

about:
  home: https://github.com/micknudsen/snpahoy
  license: MIT
  summary: ID SNP analysis for NGS sequencing
